name: 'curtaincallwp-release'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    tags:
      - "v*.*.*"
env:
  PHP_VERSION: 8.1
  NODE_VERSION: 24

jobs:
  release:
    name: Releases
    runs-on: ubuntu-latest
    steps:
      - name: 'Set output variables'
        id: vars
        shell: bash
        # tag == with v
        # version == without v
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install php
        uses: ./.github/actions/php_install
        with:
          php-version: ${{ env.PHP_VERSION }}
          composer-flags: --no-dev

      - name: Install Node
        uses: ./.github/actions/node_install
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        shell: bash
        env:
          TAG: ${{ steps.vars.outputs.version }}
          VERSION: ${{ steps.vars.outputs.version }}
        run: ./scripts/build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          name: ${{ steps.vars.outputs.tag }}
          tag_name: ${{ steps.vars.outputs.tag }}
          files: curtaincallwp-${{ steps.vars.outputs.version }}.zip
          generate_release_notes: true
